# Generated by Django 5.2.8 on 2025-11-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('code_verified', 'Code Verified'), ('done', 'Done')], default='new', max_length=20),
        ),
    ]
